# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.yusute.com
date_format: "ordinal"
title: 杜乐乐hot
subtitle: "My life and my story"
description: "Welcome to 杜乐乐hot's Blog!"
keywords: 杜乐乐hot, blog, yusute
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 杜乐乐hot
organization: yusute.com
organization_url: http://www.yusute.com
github_username: yusute
location: Beijing, China
email: yusutehot@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: home

  -
    href: /categories/
    label: categories

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: links

  -
    href: /about/
    label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yusute/yusute.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username: yusute
netease_gentie_key: 55730e22f16f4aaaaba3491e49fbf0ef
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-93472347-1
