# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
author: Jekyll Writer
description: > # this means to ignore newlines until "baseurl:"
  This theme is disigned based on Mailbox Blog, and licensed under MIT.
  This theme is also default theme for new site created by Jekyll Writer.
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/page/:num/"
twitter_username: jekyllwriter
github_username:  jekyllwriter
gems: [jekyll-paginate]
markdown: kramdown
baseurl: "/blog"